services:
  postgres:
    image: postgres:16
    container_name: codedoctor-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codedoctor

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .

    container_name: codedoctor-backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    volumes:
      - .:/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: